### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by B0IIE** [flatsiedatsie/internet-radio#1]
Hi,

I don´t understand how this is supposed to work.
I´ve added it to my gateway and edited the radio stations, but I cant select them anywhere.

edit:
I have the following reacuring log entries:
```
2019-09-08 15:16:41.033 ERROR  : internet-radio: Traceback (most recent call last):
2019-09-08 15:16:41.035 ERROR  : internet-radio:   File "/home/pi/.mozilla-iot/addons/internet-radio/main.py", line 12, in <module>
2019-09-08 15:16:41.037 ERROR  : internet-radio:     from pkg.internet_radio_adapter import InternetRadioAdapter  # noqa
2019-09-08 15:16:41.039 ERROR  : internet-radio:   File "/home/pi/.mozilla-iot/addons/internet-radio/pkg/internet_radio_adapter.py", line 14, in <module>
2019-09-08 15:16:41.040 ERROR  : internet-radio:     import requests
2019-09-08 15:16:41.042 ERROR  : internet-radio: ImportError: No module named 'requests'
2019-09-08 15:16:41.169 INFO   : Plugin: internet-radio died, code = 1 restarting after 21000
```

Dom

**Comment by flatsiedatsie** [comment]
The plugin can't find the 'requests' python module. This is strange, since I believe this should be present as standard.

Are you using the normal disk image?

**Comment by flatsiedatsie** [comment]
Hopefully the new version solves your problem.

**Comment by B0IIE** [comment]
Thanks for the update. I now was able to add the radio thing.
But unfortunatly I cant get any sound out of my speaker or headphones (both 3.5 mm audio jack) with my original gateway..

I just set up a new gateway and there it is working. Thank you for your fast reply.
